#!/bin/bash
if ping -c 1 gimplscraft.ddns.net &> /dev/null
then
    rsync -e 'ssh -p 505' -aP tiggax@gimplscraft.ddns.net:/mnt/Data/Dokumenti/Šola/Faks/ /home/tilen/Dokumenti/Faks/
    rsync -e 'ssh -p 505' -aP tiggax@gimplscraft.ddns.net:/mnt/Data/Programing/ /home/tilen/Programing/
fi
